[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nanogemm"
version = "0.3.6"
description = "Minimalist, bare-metal SIMD & Assembly GEMM engine for Python. Sub-microsecond CPU matrix multiplication for AI & scientific computing."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [
    { name = "eminsk", email = "M_N_Nik@yahoo.com" }
]
keywords = [
    "gemm",
    "matrix-multiplication",
    "simd",
    "assembly",
    "fasm",
    "avx2",
    "cpu-inference",
    "deep-learning",
    "high-performance-computing",
    "free-threaded",
    "no-gil",
    "pep-703",
    "pypy",
    "pypy3"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: C",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Mathematics",
]
dependencies = [
    "numpy>=1.20.0, <2; implementation_name == 'pypy' and python_version < '3.10'",
    "numpy>=1.20.0, <2.3.0; implementation_name != 'pypy' and python_version <= '3.13'",
    "numpy>=1.20.0; implementation_name == 'pypy' and python_version >= '3.10'",
    "numpy>=2.3.0; implementation_name != 'pypy' and python_version >= '3.14'",
    "typing-extensions>=4.0; python_version < '3.10'",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
]

[project.urls]
Homepage = "https://github.com/eminsk/nanogemm"
Repository = "https://github.com/eminsk/nanogemm"
Issues = "https://github.com/eminsk/nanogemm/issues"
